name: Assembly CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v3
      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make my_tests
          make mimuw_tests
      - name: test
        run: |
          ./build/my_tests
          ./build/mimuw_tests