name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v3
      - name: compile
        run: ./compile.sh

  test:

    runs-on: ubuntu-latest

    steps:
      - name: test
        run: ./test -color=false >> $GITHUB_OUTPUT