name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v3
      - name:
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: test
        run: ./test